### ISSUE TITLE
SoftmaxOutput not defined

### ISSUE THREAD

**Issue by philtomson** [dmlc/MXNet.jl#19]
This may just be a mismatch between the documentation and the code, but when I tried running your example (from the README) I got:

 UndefVarError: SoftmaxOutput not defined

Reported from this line:
   mx.SoftmaxOutput(name=:softmax)

When I changed it to:

  mx.Softmax(name=:softmax)

It worked.

I'm running MXNet.jl 0.0.3 with Julia 0.4.1-pre+8

**Comment by vchuravy** [comment]
You might have to update and rebuild MXNet for that.

**Comment by pluskid** [comment]
Yes, maybe 

Pkg.build("MXNet")

Should fix it.

**Comment by philtomson** [comment]
So first I tried to remove the MXNet package:

> Pkg.rm("MXNet")

And then reinstalled:

> Pkg.add("MXNet")

... but still had the same problem. I did a search for libmxnet.so and found it under ~/.julia/v0.4/.trash/MXNet/deps/src/mxnet/lib

So next I removed the ~/.julia/v0.4/.trash directory and did Pkg.add("MXNet") again.  That worked. 

So somehow it seems like that .trash directory is being found and the libmxnet.so that was there was reused initially when I did Pkg.add after Pkg.rm and of course it was out of sync. Not sure how this is handled, but maybe when the Pkg.add("MXNet") is done it should always just download mxnet and rebuild libmxnet.

**Comment by pluskid** [comment]
I'm not sure how a `.trash` directory end up being created, and how the libmxnet.so in the trash end up being found and loaded by Julia. Building is skipped only when `libxmnet.so` is found either in the system ld search path, or when the environment variable `MXNET_HOME` is set. In both case, this means the user installed libmxnet somewhere and explicitly specified its location. Otherwise, a fresh clone and re-build of libmxnet is always made when `Pkg.build("MXNET")` is run.

**Comment by philtomson** [comment]
The .trash directory was created when I did a Pkg.rm("MXNet") - I just did it again to confirm.

**Comment by pluskid** [comment]
I see. Thanks! But I do not understand how Julia find the so file in that directory. Maybe you did not restart repl?

**Comment by philtomson** [comment]
Hmm... Possible, but when I removed the .trash directory then it did go and download the mxnet code and build libmxnet.so, so I'm guessing that somehow it was able to find it in .trash.
