### ISSUE TITLE
v0.6?

### ISSUE THREAD

**Issue by mcreel** [dmlc/MXNet.jl#240]
I'm attempting to run the code in the examples directory using julia v0.6.0-pre.beta, so as to be able to switch to v0.6 when it is released. None of the examples seem to run, giving errors similar to
`julia> include("mlp-test.jl")
Error During Test
  Test threw an exception of type MethodError
  Expression: mnist_fit_and_predict(mx.SGD(lr=0.1, momentum=0.9), mx.UniformInitializer(0.01), 2) > 90
  MethodError: MXNet.mx.#FullyConnected(::Array{Any,1}, ::MXNet.mx.#FullyConnected) is ambiguous. Candidates:
    (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected, args::MXNet.mx.SymbolicNode...) in MXNet.mx                                                                                                                
    (::MXNet.mx.#kw##FullyConnected)(::Array{Any,1}, ::MXNet.mx.#FullyConnected, args::MXNet.mx.NDArray...) in MXNet.mx      `

Are there any examples that show how to use MXNet.jl with the 0.6 code base? Thanks.

**Comment by vchuravy** [comment]
So far there has been little to no effort to update MXNet.jl to 0.6, mostly due to limited time available. One problem that needs to be solved before supporting v0.6 is #170 and there are certainly more issue to crop up.

I won't have time until early June to work on support for v0.6. Help in preparring MXNet.jl for v0.6 would definitely be welcomed.

**Comment by mcreel** [comment]
The examples are running now on 0.6, so closing
