### ISSUE TITLE
Issue with Dynamically generated docstrings

### ISSUE THREAD

**Issue by pluskid** [dmlc/MXNet.jl#3]
Julia v0.4 has built-in docstring mechanism. The docstrings could be retrieved in REPL by typing question marks followed by object name. However, currently we rely on 3rd party libraries (specifically [Lexicon.jl](https://github.com/MichaelHatherly/Lexicon.jl)) to generate external markdown documents. It seems that Lexicon.jl cannot find dynamically generated documents for imported symbols, though the Julia REPL could correctly find them.

Several possible options:

* Handcraft a way to extract docstrings from Julia's module meta, and export to markdown (sounds very complicated, esp. there is very few document about the documentation system).
* Ask around and beg for help (easiest, I'll do this first)
* When importing functions from libmxnet, beside generating docstrings, also dump directly into an external markdown file (a hacky workaround, but might work)

**Comment by tqchen** [comment]
Currently R follows a code generation way to do it. Mainly because R do not support dynamically generated docstring. So there is a exporter that simply exports the wrapper along with the docstring https://github.com/dmlc/mxnet/blob/master/R-package/src/export.cc and generated here https://github.com/dmlc/mxnet/blob/master/R-package/R/mxnet_generated.R

However, I guess if Julia already supports docstring, maybe using the the dynamic one is a better way.

**Comment by pluskid** [comment]
@tqchen Thanks for the pointer! I think that might be a fallback solution I'll have to do (for now) if there is no good solution. I found an experimental branch Docile.jl that has some interaction with the new Julia v0.4 documentation system. I will try to see if that one could work for us.

**Comment by pluskid** [comment]
After painful struggling I decided to give up the current preliminary docstring system and use a simple way to create docs. I also switched to Sphinx doc system, and currently the automatically exported doc looks nice: http://mxnetjl.readthedocs.org/en/latest/index.html#api-documentation
