### ISSUE TITLE
Inconsistent Parameter Order in "mx.dot" Resulting in "dot shape error"

### ISSUE THREAD

**Issue by chyanju** [dmlc/MXNet.jl#55]
I was trying the "<a href="http://mxnetjl.readthedocs.org/en/stable/api/ndarray.html#dot">mx.dot()</a>" to calculate 2D matrix multiplication. Codes & exceptions in Julia REPL are like:
<pre><code lang="julia"># Julia REPL
julia> using MXNet
julia> A=mx.ones((5,3))
mx.NDArray(5,3)
julia> B=mx.ones((3,9))
mx.NDArray(3,9)
julia> mx.dot(A,B)
[10:41:49] ./dmlc-core/include/dmlc/logging.h:208: [10:41:49] src/ndarray/./ndarray_function.h:71: Check failed: (lshape[1]) == (rshape[0]) dot shape error: (3, 5) X (9, 3)
ERROR: MXNet.mx.MXError("[10:41:49] src/ndarray/./ndarray_function.h:71: Check failed: (lshape[1]) == (rshape[0]) dot shape error: (3, 5) X (9, 3)")
 [inlined code] from /home/joseph/.julia/v0.4/MXNet/src/base.jl:57
 in _invoke_mxfunction at /home/joseph/.julia/v0.4/MXNet/src/ndarray.jl:836
 in dot at no file
julia> mx.dot(B,A)
mx.NDArray(5,9)
</code></pre>
So I figure the order of the parameters should be like "<strong>mx.dot(rhs::NDArray,lhs::NDArray)</strong>", which is different from others, like <a href="http://mxnet.readthedocs.org/en/stable/python/ndarray.html#mxnet.ndarray.dot">Python</a>, as the following Python code works:
<pre><code lang="python"># Python REPL
>>> import mxnet as mx
>>> A=mx.nd.ones((5,3))
>>> B=mx.nd.ones((3,9))
>>> mx.ndarray.dot(A,B)
&lt;mxnet.ndarray.NDArray object at 0x7f1f00a06650&gt;
</code></pre>
And is this specific in Julia or it is a bug? Should it be "<strong>mx.dot(lhs::NDArray,rhs::NDArray)</strong>"?

**Comment by chyanju** [comment]
BTW, the mxnet version is  
"MXNet"             => v"0.0.7"
in Julia, and the Python I tested above is using the same libmxnet.so as Julia does.

**Comment by pluskid** [comment]
In my opinion, the semantic of `dot(A,B)` should be `A' * B` -- (A transposed) x (B). The inconsistency should be a bug at some place. I will have a look. Thanks for reporting.

**Comment by pluskid** [comment]
In Julia (and R, Matlab), the `NDArray` has column-majoring. So a matrix with shape `(2, 3)` is a matrix with shape `(3, 2)` in libmxnet. The implementation of `dot` in libmxnet checks
```
CHECK_EQ(lshape[1], rshape[0])
```
So in Python, `dot` of matrices `(2, 3)` and `(3, 8)` checks pass because `lshape[1]` is 3, and `rshape[0]` is 3.

But in Julia (and R, Matlab), the check will fail because `lshape[1]` is 2 and `rshape[0]` is 8.

One possible solution is when defining `dot` in Julia (and R, matlab), swap the `lhs` with `rhs`. Semantically, passing a matrix from Julia to libmxnet (and back) means a transpose. So `(A' * B')' = B * A`. Though this is quite hacky and obscure, as we need to match function name in automatic operator defining of NDArray. @tqchen @mli I guess the R and Matlab bindings have similar issue.

**Comment by pluskid** [comment]
A workaround is added to swap the arguments for `dot`. However, we need to worry about consistency also in the symbolic API side.

**Comment by tqchen** [comment]
This problem only occurs for few non-elementwise cases for now, e.g. dot, The symbolic API(FullyConnected) is fine as weight and bias are properly specified

**Comment by vchuravy** [comment]
https://github.com/dmlc/MXNet.jl/pull/123#issuecomment-244207944

**Comment by pluskid** [comment]
This should have already been fixed in v0.1.0
