### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by cbecker** [dmlc/MXNet.jl#7]
First thanks for providing this wonderful package.

When running the example in README.MD I am getting
```julia
julia> mx.fit(model, optimizer, train_provider, n_epoch=20, eval_data=eval_provider)
ERROR: unrecognized keyword argument "n_epoch"
```

I searched on the code but I am not sure where that is coming from.

**Comment by pluskid** [comment]
If you are using the release version, please run the examples in the locally installed folder. Otherwise please checkout the gut version. The error is due to a renaming of one of the argument in the method epoch_stop to n_epoch. I'm sorry things are changing a bit as I'm still designing the interface.

**Comment by cbecker** [comment]
Oh I see, no problem, I will checkout the master branch. Thanks!
