### ISSUE TITLE
MXListFunctions ccall error

### ISSUE THREAD

**Issue by cbecker** [dmlc/MXNet.jl#8]
I am trying with the master checkout and after successfully building MXNet I try to use it and I get
```julia
julia> using MXNet
ERROR: InitError: ccall: could not find function MXListFunctions in library 
 [inlined code] from /home/cjb/.julia/v0.4/MXNet/src/base.jl:47
 in _import_ndarray_functions at /home/cjb/.julia/v0.4/MXNet/src/ndarray.jl:471
 in __init__ at /home/cjb/.julia/v0.4/MXNet/src/base.jl:24
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
during initialization of module mx
```

could this have to do with a version issue?

**Comment by pluskid** [comment]
@cbecker This is due to the issue that libmxnet.so cannot be loaded. Either because MXNet.jl cannot find it or the file is there but load failed due to unsatisfied external dependency. Unfortunately, `Libdl` in Julia just silently eat all error messages. I will try to provide an error message there.

But to help figure this out, are you using the automatically compiled libmxnet or are you building a separate one? In the latter case, you will need to set `MXNET_HOME` environment variable.

**Comment by cbecker** [comment]
Thanks, I see, I was expecting a clearer error.
I compiled it automatically, and `MXNET_LIB` seems to point to the right direction
```julia
MXNET_LIB = "/home/cjb/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so"
```

and `ldd` doesn't show any missing linked libraries from libmxnet.so.

**Comment by pluskid** [comment]
This is definitely strange. So do you mean after `using MXNet` (though it failed due to an error), `mx.MXNET_HOME` is pointing to the path you showed above? Just to make sure the library is compiled correctly, does
```
$ nm ~/work/mxnet/mxnet/lib/libmxnet.so | grep MXListFunctions
```
find the function for you?

**Comment by cbecker** [comment]
yes, exactly. Yes it finds it, I will see if I can find out more. If you have any other suggestions let me know.
```bash
~ ᐅ nm /home/cjb/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so | grep MXListFunctions
0000000000211770 T MXListFunctions
```

**Comment by pluskid** [comment]
Maybe in a Julia REPL, try to explicitly access the function symbol by
```
julia> hdr = Libdl.dlopen(mx.MXNET_LIB)
Ptr{Void} @0x00007fca2ad64f10

julia> Libdl.dlsym(hdr, :MXListFunctions)
Ptr{Void} @0x0000000315a54dc0
```
and see if you can get a handle correctly?

**Comment by cbecker** [comment]
Weird, I just tried that and it worked, and `using MXNet` now works, I am really lost here..
Maybe it had to do with `ldconfig` or some other cache, sorry for the false alarm.

**Comment by cbecker** [comment]
oh I think I found out. I tried removing and re-installing MXNet, and the issue is that it `mx.MXNET_LIB` is empty in the julia cache file, so it is necessary to touch a file, like `io.jl`, so that when you do `using MXNet` again it will re-build the cache and pick the right path for `MXNET_LIB`

**Comment by pluskid** [comment]
Yes, `mx.MXNET_LIB` gets precompiled as a constant due to the conventional way Julia handling `ccall`. So even if you set `MXNET_HOME` properly afterwards, if you do not do the pre-compilation of the Julia Module, it still will not find. I just added hack to touch the file itself whenever loading libmxnet.so is not found, so that it will always update the precompile the next time. Hope this will work better.

**Comment by cbecker** [comment]
Thanks that should do.
Another unrelated thing, prediction seems much much slower than training, which surprises me as during training a forward pass is needed as well. Is there a faster way tha calling `mx.predict` ? I am trying to predict 300k samples at the same time (with 100 batch size).

**Comment by pluskid** [comment]
@cbecker Are you using multiple devices? Currently parallelization is only implemented for training. The prediction step only uses the first device in the provided device list. If multi-device parallelization is needed for prediction, please open an issue and I will try to add that later. If it is not about multi-device, this is then quite unexpected. Could you also open an issue? Thanks!

**Comment by pluskid** [comment]
@cbecker Another potential problem is because by default `mx.predict` accumulate all the outputs and return the after the whole data pass. There is a overloaded `mx.predict` that accept a callback. When you have a large test set, it might be better to use the callback to write the prediction results to a file directly. However, I do not see why accumulating in memory could be slower than writing to file (provided you have not run out of memory yet).

**Comment by cbecker** [comment]
The trick seems to be to set the right batchsize to avoid extra allocations, for example:

I tried using a callback with
```julia
function predict(model, idxs)

	x = map(Float32, zData[idxs,:]')
	test_provider = mx.ArrayDataProvider( x, batch_size=100 )

	p = Any[]
	function callback(x)
		push!(p, x[1])
	end

	mx.predict(callback, model, test_provider, overwrite=true)
	return p
end

julia> @time predict(m,1:10000)
14.423960 seconds (5.05 k allocations: 16.682 MB)
```

and the bottleneck is still there, though not at `push!()` but at https://github.com/dmlc/MXNet.jl/blob/master/src/model.jl#L173 according to profile, and digging in further at https://github.com/dmlc/MXNet.jl/blob/master/src/io.jl#L265 and then https://github.com/dmlc/MXNet.jl/blob/7e86c8f7f001977f5429762112824b0a7d50e32f/src/base.jl#L47

Then, if I set `batch_size=size(x,2)` it runs extremely fast ;)
So I think we've found the problem.

**Comment by pluskid** [comment]
@cbecker I see. Thanks for do the profiling. I think this makes sense. Because prediction has much less computational cost than training (no backward or parameter updating). So the bottleneck becomes processing the data. I think using as large mini-batch size as possible in the prediction makes sense (I will try to add that as a note to the document).

**Comment by cbecker** [comment]
Great, thanks. How can parallelization be used for training? I found that I can set to use a specific CPU but I am not sure how to specify many.

also I will make a PR soon, I implemented ADAM SGD and fixed an issue with the example in README.md.

**Comment by pluskid** [comment]
@cbecker Great!

To do multiple devices, you can do, for example,
```
model = mx.FeedForward(mlp, context=[mx.cpu(0), mx.cpu(1)]
```
But I'm not sure it will improve for CPUs. As by default the BLAS will use a lot of cores to do computation. So explicitly using multiple CPU cores to do data parallelization might actually hurt the performance because extra communication and synchronization is needed. This feature is primarily designed for large models and multiple GPU devices. See the [cifar10 example](https://github.com/dmlc/MXNet.jl/blob/master/examples/cifar10/cifar10.jl#L76).

**Comment by dioptre** [comment]
+1 I got the same _import_ndarray_functions error that was fixed by doing a git update in the MXNet directory.
